format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$jobs\
$fill\
$deno\
$rust\
$nodejs\
$golang\
$terraform\
$aws\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "bold blue"
read_only = " "
truncate_to_repo = true

[aws]
format = 'on [$symbol$profile]($style) '

[git_branch]
truncation_length = 6
truncation_symbol = ''
style = 'bold purple'
