set -g @plugin 'tmux-plugins/tpm'
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",screen-256color:Tc"

# Plugins
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g mouse on

# Catppuccin config
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #{b:pane_current_path}"
set -g @catppuccin_window_current_text " #{b:pane_current_path}"
set -g @catppuccin_date_time_text "%a %b %d %l:%M %p"

# Prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Pane resizing
bind -r ^ last-window
bind -r k resize-pane -U 5
bind -r j resize-pane -D 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5
bind -r m resize-pane -Z

# Splits
unbind '"'
bind - split-window -v
unbind %
bind | split-window -h

# Status line
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -gF status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -gF @catppuccin_battery_expanded "#{E:@catppuccin_status_battery}"
set -ag status-right "#{?#{==:#{battery_status},discharging},#{E:@catppuccin_battery_expanded},}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
